# Generated by Django 2.1.5 on 2019-03-03 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallphotowrapper',
            name='workload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wall_photo_wrappers', to='workload.Workload'),
        ),
    ]
