# Generated by Django 2.1.5 on 2019-03-13 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sketch',
            old_name='comment',
            new_name='sketch_description',
        ),
    ]
