# Generated by Django 2.1.5 on 2019-03-03 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0002_auto_20190303_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallphotowrapper',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photo_wrapper', to='workload.Location'),
        ),
    ]
