# Generated by Django 2.1.5 on 2019-01-22 17:30

import anyart_api.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0003_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='upload',
            field=models.FileField(storage=anyart_api.storage_backends.PrivateMediaStorage, upload_to=''),
        ),
    ]
