# Generated by Django 2.1.5 on 2019-01-22 19:01

import anyart_api.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0004_auto_20190122_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='upload',
            field=models.FileField(storage=anyart_api.storage_backends.PrivateMediaStorage(), upload_to='documents'),
        ),
    ]
