# Generated by Django 2.1.5 on 2019-01-23 09:14

import anyart_api.storage_backends
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workload', '0005_auto_20190122_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(storage=anyart_api.storage_backends.PrivateMediaStorage(), upload_to='legal_agreements')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(blank=True, max_length=200, null=True)),
                ('lng', models.FloatField()),
                ('lat', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PermissionLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(storage=anyart_api.storage_backends.PrivateMediaStorage(), upload_to='permission_letters')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhotoAfter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(storage=anyart_api.storage_backends.PublicMediaStorage(), upload_to='after_photos')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Restriction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workload.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Sketch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SketchImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.FileField(storage=anyart_api.storage_backends.PublicMediaStorage(), upload_to='sketches')),
                ('sketch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workload.Sketch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WallPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(storage=anyart_api.storage_backends.PublicMediaStorage(), upload_to='wall_photos')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WallPhotoWrapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('requirements', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='wallphotowrapper',
            name='workload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workload.Workload'),
        ),
        migrations.AddField(
            model_name='wallphoto',
            name='wrapper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workload.WallPhotoWrapper'),
        ),
        migrations.AddField(
            model_name='sketch',
            name='workload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workload.Workload'),
        ),
        migrations.AddField(
            model_name='photoafter',
            name='workload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workload.Workload'),
        ),
        migrations.AddField(
            model_name='permissionletter',
            name='workload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workload.Workload'),
        ),
        migrations.AddField(
            model_name='legalagreement',
            name='workload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workload.Workload'),
        ),
    ]
