# Generated by Django 2.1.5 on 2019-01-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0006_auto_20190123_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallphotowrapper',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
