# Generated by Django 2.1.5 on 2019-01-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0008_auto_20190124_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='workload',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='workload',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'InitialUpload'), (2, 'FirstSketchesHaveAdded'), (3, 'SketchesBeenApprovedByCouncil'), (5, 'LegalAgreementIsReady'), (8, 'StreetArtIsComplete'), (13, 'StreetArtCorrespondsToAgreement')], default=1),
        ),
    ]
