# Generated by Django 2.1.5 on 2019-01-25 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0010_auto_20190124_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallphotowrapper',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workload.Location'),
        ),
    ]
