# Generated by Django 2.1.5 on 2019-01-28 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0013_auto_20190128_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallphoto',
            name='wrapper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wall_photos', to='workload.WallPhotoWrapper'),
        ),
    ]
