# Generated by Django 2.1.5 on 2019-01-28 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0014_auto_20190128_2314'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
