# Generated by Django 2.1.5 on 2019-02-12 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0015_delete_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoafter',
            name='workload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='after_photos', to='workload.Workload'),
        ),
        migrations.AlterField(
            model_name='sketchimage',
            name='sketch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sketches', to='workload.Sketch'),
        ),
    ]
