# Generated by Django 2.1.5 on 2019-02-14 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0016_auto_20190212_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sketch',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
