# Generated by Django 2.1.5 on 2019-02-16 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0017_auto_20190214_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legalagreement',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='permissionletter',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='photoafter',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='sketchimage',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='wallphoto',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='workload',
            old_name='created',
            new_name='created_at',
        ),
    ]
