# Generated by Django 2.1.5 on 2019-02-16 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0018_auto_20190216_1813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sketch',
            options={'verbose_name_plural': 'sketches'},
        ),
    ]
