# Generated by Django 2.1.5 on 2019-02-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0020_auto_20190220_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='sketch',
            name='comment',
            field=models.TextField(blank=True, default='Not provided'),
        ),
    ]
