# Generated by Django 2.1.5 on 2019-03-22 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workload', '0002_auto_20190313_1357'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approvers', models.ManyToManyField(related_name='approval_groups', to=settings.AUTH_USER_MODEL)),
                ('workload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workload.Workload')),
            ],
        ),
        migrations.CreateModel(
            name='SketchDecision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_role', models.CharField(choices=[('Member1', 'Member1'), ('Member2', 'Member2'), ('Member3', 'Member3')], max_length=100)),
                ('vote', models.IntegerField(choices=[(0, 'Disapproved'), (1, 'Approved'), (13, 'Veto')], null=True)),
                ('approval_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.ApprovalGroup')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sketch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workload.Sketch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SketchVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(choices=[(1, 'Like'), (0, 'Dislike')])),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sketch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workload.Sketch')),
            ],
        ),
        migrations.CreateModel(
            name='WallPhotoWrapperDecision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_role', models.CharField(choices=[('Member1', 'Member1'), ('Member2', 'Member2'), ('Member3', 'Member3')], max_length=100)),
                ('vote', models.IntegerField(choices=[(0, 'Disapproved'), (1, 'Approved'), (13, 'Veto')], null=True)),
                ('approval_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.ApprovalGroup')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wall_photo_wrapper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workload.WallPhotoWrapper')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
