# Generated by Django 2.1.5 on 2019-03-02 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workload', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approvers', models.ManyToManyField(related_name='approval_groups', to=settings.AUTH_USER_MODEL)),
                ('workload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workload.Workload')),
            ],
        ),
        migrations.CreateModel(
            name='SketchDecision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_role', models.CharField(max_length=100)),
                ('vote', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sketch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workload.Sketch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WallPhotoWrapperDecision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_role', models.CharField(max_length=100)),
                ('vote', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wall_photo_wrapper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workload.WallPhotoWrapper')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
