# Generated by Django 2.1.5 on 2019-03-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sketchdecision',
            name='group_role',
            field=models.CharField(choices=[('Tourism Management', 'Tourism Management'), ('IT management', 'IT management'), ('History Preservation Management', 'History Preservation Management'), ('Main Architect', 'Main Architect'), ('Owner', 'Owner'), ('Art Expert', 'Art Expert')], max_length=100),
        ),
        migrations.AlterField(
            model_name='wallphotowrapperdecision',
            name='group_role',
            field=models.CharField(choices=[('Tourism Management', 'Tourism Management'), ('IT management', 'IT management'), ('History Preservation Management', 'History Preservation Management'), ('Main Architect', 'Main Architect'), ('Owner', 'Owner'), ('Art Expert', 'Art Expert')], max_length=100),
        ),
    ]
