# Generated by Django 2.1.5 on 2019-03-25 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0002_auto_20190325_2231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sketchdecision',
            options={'permissions': [('can_approve_object', 'Can Approve Object'), ('can_disapprove_object', 'Can Disapprove Object'), ('can_veto_object', 'Can Veto Object')]},
        ),
        migrations.AlterModelOptions(
            name='wallphotowrapperdecision',
            options={'permissions': [('can_approve_object', 'Can Approve Object'), ('can_disapprove_object', 'Can Disapprove Object'), ('can_veto_object', 'Can Veto Object')]},
        ),
    ]
