# Generated by Django 2.1.5 on 2019-03-02 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rights', models.CharField(choices=[('basic', 'BasicUser'), ('artist', 'Artist'), ('gov', 'GovernmentRepresentative')], max_length=50)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artist_user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BasicUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rights', models.CharField(choices=[('basic', 'BasicUser'), ('artist', 'Artist'), ('gov', 'GovernmentRepresentative')], max_length=50)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basic_user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GovernmentUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rights', models.CharField(choices=[('basic', 'BasicUser'), ('artist', 'Artist'), ('gov', 'GovernmentRepresentative')], max_length=50)),
                ('authority', models.CharField(choices=[('lcc', 'Lviv City Council')], max_length=100)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gov_user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
