# Generated by Django 2.1.5 on 2019-03-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rights',
            field=models.CharField(choices=[('basic', 'BasicUser'), ('artist', 'Artist'), ('gov', 'GovernmentRepresentative')], default='basic', max_length=50),
        ),
    ]
