# Generated by Django 2.1.5 on 2019-03-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governmentuserprofile',
            name='authority',
            field=models.CharField(choices=[('Culture Management', 'Culture Management'), ('Tourism Management', 'Tourism Management'), ('IT management', 'IT management'), ('History Preservation Management', 'History Preservation Management'), ('Main Architect', 'Main Architect')], default='IT management', max_length=100),
        ),
    ]
