# Generated by Django 2.1.5 on 2019-01-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rights',
            field=models.CharField(choices=[('basic', 'basic'), ('artist', 'artist'), ('gov', 'gov')], max_length=50),
        ),
    ]
