# Generated by Django 2.1.5 on 2019-01-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_auto_20190116_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rights',
            field=models.CharField(choices=[('bas', 'BasicUser'), ('art', 'Artist'), ('gov', 'GovernmentRepresentative')], max_length=50),
        ),
    ]
