# Generated by Django 2.1.5 on 2019-03-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_auto_20190313_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governmentuserprofile',
            name='authority',
            field=models.CharField(choices=[('lcc', 'Lviv City Council'), ('Authority1', 'Authority1'), ('Authority2', 'Authority2'), ('Authority3', 'Authority3')], max_length=100),
        ),
    ]
