# Generated by Django 2.1.5 on 2019-03-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_auto_20190321_1754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='governmentuserprofile',
            options={'permissions': [('can_approve_object', 'Can Approve Object'), ('can_disapprove_object', 'Can Disapprove Object'), ('can_veto_object', 'Can Veto Object')]},
        ),
        migrations.AlterField(
            model_name='governmentuserprofile',
            name='authority',
            field=models.CharField(choices=[('Culture Management', 'Culture Management'), ('Tourism Management', 'Tourism Management'), ('IT management', 'IT management'), ('History Preservation Management', 'History Preservation Management'), ('Main Architect', 'Main Architect')], max_length=100),
        ),
    ]
