# Generated by Django 2.1.5 on 2019-02-16 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_auto_20190124_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='owner',
        ),
    ]
