# Generated by Django 2.1.5 on 2019-03-25 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_auto_20190325_2231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='governmentuserprofile',
            options={},
        ),
    ]
